server:
  port: 8080

mysql:
  host: ""
  port: 3306
  user: root
  passwd: ""
  db: xdance
  max_connects: 100
  max_idle_connects: 100
  conn_max_idle_time: 600
  conn_max_lifetime: 3600

redis:
  host: ""
  port: 6379
