server:
  port: 8080

mysql:
  host: "db-dev.cvq6tifqs4ja.us-east-1.rds.amazonaws.com"
  port: 3306
  user: root
  passwd: "ZsXzNz778m3qIcVCBWmD"
  db: xdance
  max_connects: 100
  max_idle_connects: 100
  conn_max_idle_time: 600
  conn_max_lifetime: 3600

redis:
  host: "redis-dev.uewp4i.ng.0001.use1.cache.amazonaws.com"
  port: 6379